Repository wanzenried/eksamensOpgave, pull requests merged in 2020-04, with the labels that each got.

#18 added delegations
  eksamensdokumenter/problemformulering.md
Labels: eksamensregler

#20 Opgavens omfang
  eksamensdokumenter/problemformulering.md
Labels: eksamensregler

#22 Capitilization
  eksamensdokumenter/problemformulering.md
Labels: eksamensregler

#21 added eventual additions
  eksamensdokumenter/problemformulering.md
Labels: eksamensregler

#23 Den individuelle eksaminands fokus
  eksamensdokumenter/problemformulering.md
Labels: documentation, eksamensregler

#24 tilføjede problemformulering til forsiden
  README.md
  docs/README.md
  docs/smb1-1.jpg
Labels: documentation

#27 Add player character plus temporary boxes for testing
  index.html
  player.js
  sketch.js
Labels: enhancement, top priority

#28 making physics accesible to all
  index.html
  physics.js
  player.js
Labels: enhancement

#29 Resizer
  index.html
  resizer.js
  sketch.js
Labels: enhancement

#33 Resizer
  resizer.js
  sketch.js
Labels: documentation

#34 Hostile interraction
  physics.js
  player.js
  sketch.js
Labels: enhancement

#37 Add configfile
  config.json
  index.html
  player.js
  sketch.js
Labels: enhancement

#42 Sidescrolling
  config.json
  physics.js
  player.js
  sketch.js
Labels: enhancement

#44 fixed dat collison
  physics.js
  player.js
Labels: bugfix

#45 Update blocks.js
  blocks.js
Labels: documentation
