Repository wanzenried/eksamensOpgave, pull requests merged in 2020-05, with the labels that each got.

#46 World creation
  blocks.js
  collectibles.js
  index.html
  level.js
  map.bmp
  physics.js
  player.js
  sketch.js
Labels: enhancement, world building

#48 Coll pick up
  blocks.js
  collectibles.js
  player.js
  sketch.js
Labels: powerups

#52 Fixing collisions
  blocks.js
  level.js
  physics.js
  player.js
  sketch.js
Labels: bugfix

#61 Add score
  blocks.js
  sketch.js
Labels: point system

#66 Points and timer
  blocks.js
  player.js
  sketch.js
Labels: point system

#65 Jump hight&speed
  config.json
  physics.js
  player.js
Labels: bugfix
